# Generated by Django 6.0.5 on 2026-05-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodsession',
            name='context_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
