# Generated by Django 6.0.5 on 2026-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_moodsession_context_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodsession',
            name='artist_requested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
